### PR TITLE
refactor: rewrote onehot loops, ran cargo fmt

### PR DESCRIPTION
**Pull request by mesejo**

### CODE REVIEW

**Comment by mesejo** [comment]
There seems to be a bug, even though cargo test is passing

**Comment by hussainsultan** [comment]
Ahh, the bug in `src/bin/mushrooms_prediction.rs` since I did not update it. I will push a fix.

**Comment by hussainsultan** [comment]
LGTM

**Review by hussainsultan — COMMENTED** [review]
LGTM

**Pull request merged**
